apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-uploads-pv
  labels:
    type: local
    app: frontend
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/uploads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-uploads-pvc
  namespace: photoverify
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
